/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'courseId' : bigint,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'level' : Level,
}
export type Level = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserAccount {
  'username' : string,
  'fullName' : string,
  'email' : string,
  'passwordHash' : string,
  'phone' : string,
  'address' : string,
  'profileBio' : string,
  'reason' : string,
  'createdAt' : bigint,
  'isDisabled' : boolean,
  'enrolledCourse' : [] | [string],
  'assessmentScore' : [] | [bigint],
  'assessmentPassed' : [] | [boolean],
}
export type RegisterResult = { 'ok' : null } | { 'err' : string };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChapter' : ActorMethod<[bigint, string, string, bigint], bigint>,
  'addCourse' : ActorMethod<[string, string, Level], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChapter' : ActorMethod<[bigint], undefined>,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'enrollInCourse' : ActorMethod<[bigint], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllEnrollments' : ActorMethod<[], Array<[Principal, Array<bigint>]>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerCourseProgress' : ActorMethod<
    [bigint],
    { 'completedChapters' : Array<bigint>, 'enrolled' : boolean }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChaptersByCourse' : ActorMethod<[bigint], Array<Chapter>>,
  'getCompletedChapters' : ActorMethod<[], Array<bigint>>,
  'getCourseEnrollments' : ActorMethod<[], Array<bigint>>,
  'getUserCourseProgress' : ActorMethod<
    [Principal, bigint],
    { 'completedChapters' : Array<bigint>, 'enrolled' : boolean }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markChapterComplete' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateChapter' : ActorMethod<
    [bigint, bigint, string, string, bigint],
    undefined
  >,
  'updateCourse' : ActorMethod<[bigint, string, string, Level], undefined>,
  // User account management
  'registerUser' : ActorMethod<[string, string, string, string, string, string, string, string, bigint], RegisterResult>,
  'loginUser' : ActorMethod<[string, string], [] | [UserAccount]>,
  'getMaskedEmailByUsername' : ActorMethod<[string], [] | [string]>,
  'saveAssessmentResult' : ActorMethod<[string, bigint, boolean], boolean>,
  'getAllRegisteredUsers' : ActorMethod<[], Array<UserAccount>>,
  'getUserByUsername' : ActorMethod<[string], [] | [UserAccount]>,
  'adminResetUserPassword' : ActorMethod<[string, string], boolean>,
  'adminSetUserDisabled' : ActorMethod<[string, boolean], boolean>,
  'adminDeleteUser' : ActorMethod<[string], boolean>,
  'adminAssignCourse' : ActorMethod<[string, [] | [string]], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
