/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Level = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'level' : Level,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'courseId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChapter' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addCourse' : IDL.Func([IDL.Text, IDL.Text, Level], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChapter' : IDL.Func([IDL.Nat], [], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'enrollInCourse' : IDL.Func([IDL.Nat], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllEnrollments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Nat)))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerCourseProgress' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'completedChapters' : IDL.Vec(IDL.Nat),
          'enrolled' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChaptersByCourse' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
  'getCompletedChapters' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getCourseEnrollments' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserCourseProgress' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [
        IDL.Record({
          'completedChapters' : IDL.Vec(IDL.Nat),
          'enrolled' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markChapterComplete' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChapter' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateCourse' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Level], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Level = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'level' : Level,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChapter' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addCourse' : IDL.Func([IDL.Text, IDL.Text, Level], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChapter' : IDL.Func([IDL.Nat], [], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'enrollInCourse' : IDL.Func([IDL.Nat], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllEnrollments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Nat)))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerCourseProgress' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'completedChapters' : IDL.Vec(IDL.Nat),
            'enrolled' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChaptersByCourse' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
    'getCompletedChapters' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getCourseEnrollments' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserCourseProgress' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [
          IDL.Record({
            'completedChapters' : IDL.Vec(IDL.Nat),
            'enrolled' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markChapterComplete' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChapter' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateCourse' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Level], [], []),
  });
};

export const init = ({ IDL }) => { return []; };